#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication snappyHexMesh -overwrite

# set the initial fields
rm -rf 0
cp -rf 0.org 0

# run the solver
runApplication decomposePar
runParallel $application
runApplication reconstructPar

gnuplot plot.p
