#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`


runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet
runApplication createPatch -overwrite
runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite

cp -r 0.orig 0

runApplication setFields

runApplication $application

#runApplication decomposePar -force
#runParallel $application
#runApplication reconstructPar -noFunctionObjects

#------------------------------------------------------------------------------
